# Generated by Django 5.1.3 on 2024-12-14 15:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=510,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "contact",
                    models.EmailField(max_length=254, verbose_name="Kontakt Email"),
                ),
                ("start_date", models.DateField(verbose_name="Startdatum")),
                ("end_date", models.DateField(verbose_name="Enddatum")),
                ("comment", models.TextField(blank=True, verbose_name="Kommentar")),
                (
                    "number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="Anzahl Accounts",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Gültigkeit in Tagen"
                    ),
                ),
                (
                    "nameprefix",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Prefix muss mit Buchstabe beginnen und enden und darf nur Buchstaben und Zahlen enthalten",
                                regex="^[a-zA-Z][a-zA-Z0-9]*[a-zA-Z]$",
                            ),
                            django.core.validators.MinLengthValidator(2),
                        ],
                        verbose_name="Prefix",
                    ),
                ),
                (
                    "seed",
                    models.CharField(
                        blank=True, max_length=510, verbose_name="Seed für Passwörter"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Unbestätigt"),
                            (1, "Aktiv"),
                            (2, "Gebannt"),
                            (-1, "Gelöscht"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ersteller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veranstaltung",
                "verbose_name_plural": "Veranstaltungen",
                "ordering": ["-created_at"],
                "permissions": [("event_access", "Can manage events")],
            },
        ),
        migrations.CreateModel(
            name="EventGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-Mail Adresse"
                    ),
                ),
                ("password", models.CharField(max_length=510, verbose_name="Passwort")),
                ("name", models.CharField(max_length=510, verbose_name="Name")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Unbestätigt"),
                            (1, "Aktiv"),
                            (2, "Gebannt"),
                            (-1, "Gelöscht"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Startdatum"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enddatum"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="events.event",
                        verbose_name="Veranstaltung",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_sponsored",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gastgeber:in",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veranstaltungsgast",
                "verbose_name_plural": "Veranstaltungsgäste",
                "ordering": ["-created_at"],
            },
        ),
    ]
