# Generated by Django 5.1.3 on 2025-01-17 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_eventguest_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="nameprefix",
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Prefix darf nur Buchstaben, Zahlen und die Zeichen "_-" enthalten',
                        regex="^[a-zA-Z0-9_\\-]+$",
                    ),
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(10),
                ],
                verbose_name="Prefix",
            ),
        ),
    ]
