# Generated by Django 5.1.3 on 2025-02-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_event_comment_alter_event_contact_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-created_at"],
                "permissions": [("events_access", "Can manage events")],
                "verbose_name": "Veranstaltung",
                "verbose_name_plural": "Veranstaltungen",
            },
        ),
    ]
