# Generated by Django 5.1.3 on 2024-12-18 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "username",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-Mail Adresse"
                    ),
                ),
                ("password", models.CharField(max_length=510, verbose_name="Passwort")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Unbestätigt"),
                            (1, "Aktiv"),
                            (2, "Gebannt"),
                            (-1, "Gelöscht"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Startdatum"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enddatum"
                    ),
                ),
                ("name", models.CharField(max_length=510, verbose_name="Name")),
                ("duration", models.IntegerField(default=7)),
                ("extension_count", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True, verbose_name="Kommentar")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_sponsored",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gastgeber:in",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Guest",
        ),
    ]
