# Generated by Django 5.1.3 on 2025-01-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0002_guestaccount_delete_guest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestaccount",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (3, "3 Tage"),
                    (7, "7 Tage"),
                    (14, "2 Wochen"),
                    (28, "4 Wochen"),
                ],
                default=7,
            ),
        ),
        migrations.AlterField(
            model_name="guestaccount",
            name="username",
            field=models.EmailField(
                error_messages={
                    "unique": "Ein Gastzugang mit dieser E-Mail-Adresse existiert bereits."
                },
                max_length=254,
                unique=True,
                verbose_name="E-Mail-Adresse",
            ),
        ),
    ]
