# Generated by Django 5.1.3 on 2025-01-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0003_alter_guestaccount_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestaccount",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (3, "3 Tage"),
                    (7, "7 Tage"),
                    (14, "2 Wochen"),
                    (28, "4 Wochen"),
                ],
                default=7,
                verbose_name="Zugangsdauer",
            ),
        ),
        migrations.AlterField(
            model_name="guestaccount",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Unbestätigt"),
                    (1, "Aktiv"),
                    (2, "Gebannt"),
                    (-1, "Gelöscht"),
                    (-2, "Endgültig gelöscht"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
    ]
