# Generated by Django 5.1.3 on 2025-01-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0004_alter_guestaccount_duration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guestaccount",
            options={
                "permissions": [("sponsoring_access", "Can access guest sponsoring")]
            },
        ),
    ]
