# Generated by Django 5.1.3 on 2025-01-21 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0005_alter_guestaccount_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guestaccount",
            name="temp_owner_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Temporäre Gastgeber Email",
            ),
        ),
        migrations.AlterField(
            model_name="guestaccount",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_sponsored",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gastgeber:in",
            ),
        ),
    ]
