name: Bug report
description: Something is not working
title: "[BUG] Concise description of the issue"
labels: ["bug", "unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ Please remember: issues are for *bugs*
        That is, something you believe affects every single user of mysel, not just you. If you're not sure, start with one of the other options below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.
      placeholder: |
        Currently mysel does not work when...

        [Screenshot if applicable]
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Webserver logs
      description: Logs from the web server related to your issue.
      render: bash
    validations:
      required: true
  - type: textarea
    id: logs_browser
    attributes:
      label: Browser logs
      description: Logs from the web browser related to your issue, if needed
      render: bash
  - type: input
    id: version
    attributes:
      label: mysel version
      placeholder: e.g. 1.6.0
    validations:
      required: true
  - type: input
    id: host-os
    attributes:
      label: Host OS
      description: Host OS of the machine running paperless-ngx. Please add the architecture (uname -m) if applicable.
      placeholder: e.g. Archlinux / Ubuntu 20.04 / Raspberry Pi `arm64`
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser you are using, if relevant.
      placeholder: e.g. Chrome, Safari
  - type: textarea
    id: config-changes
    attributes:
      label: Configuration changes
      description: Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`.
  - type: checkboxes
    id: required-checks
    attributes:
      label: Please confirm the following
      options:
        - label: I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
          required: true
        - label: I have already searched for relevant existing issues and discussions before opening this report.
          required: true
        - label: I have updated the title field above with a concise description.
          required: true
