# Generated by Django 5.1.3 on 2025-01-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emaildevice", "0002_emaildevice_end_date_emaildevice_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emaildevice",
            name="realm",
        ),
    ]
