# Generated by Django 5.1.3 on 2025-01-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emaildevice", "0003_remove_emaildevice_realm"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emaildevice",
            options={
                "permissions": [("emaildevice_access", "Can manage Email accounts")],
                "verbose_name": "Email Account",
                "verbose_name_plural": "Email Accounts",
            },
        ),
    ]
