#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${ROUNDCUBEMAIL_DB_USER} WITH PASSWORD '${ROUNDCUBEMAIL_DB_PASSWORD}';
	CREATE DATABASE ${ROUNDCUBEMAIL_DB_NAME};
	GRANT ALL PRIVILEGES ON DATABASE ${ROUNDCUBEMAIL_DB_NAME} TO ${ROUNDCUBEMAIL_DB_USER};
	ALTER DATABASE ${ROUNDCUBEMAIL_DB_NAME} OWNER TO ${ROUNDCUBEMAIL_DB_USER};
	GRANT ALL ON SCHEMA public TO ${ROUNDCUBEMAIL_DB_USER};
EOSQL

