# Generated by Django 5.1.3 on 2024-12-14 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EduroamAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "username",
                    models.CharField(
                        max_length=510, unique=True, verbose_name="Benutzername"
                    ),
                ),
                ("password", models.CharField(max_length=510, verbose_name="Passwort")),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=510, verbose_name="Kommentar"
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        default="thga.de", max_length=510, verbose_name="Realm"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Aktiv"), (1, "Gebannt"), (-1, "Gelöscht")],
                        default=0,
                        verbose_name="Status",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eduroam_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Besitzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eduroam Account",
                "verbose_name_plural": "Eduroam Accounts",
                "permissions": [("eduroam_access", "Can manage eduroam accounts")],
            },
        ),
    ]
