# Generated by Django 5.1.3 on 2024-12-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eduroam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eduroamaccount",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Unbestätigt"),
                    (1, "Aktiv"),
                    (2, "Gebannt"),
                    (-1, "Gelöscht"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
    ]
