# Generated by Django 5.1.3 on 2025-01-18 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eduroam", "0003_eduroamaccount_end_date_eduroamaccount_start_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eduroamaccount",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_sponsored",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gastgeber:in",
            ),
        ),
        migrations.AlterField(
            model_name="eduroamaccount",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Unbestätigt"),
                    (1, "Aktiv"),
                    (2, "Gebannt"),
                    (-1, "Gelöscht"),
                    (-2, "Endgültig gelöscht"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="eduroamaccount",
            name="username",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="E-Mail Adresse"
            ),
        ),
    ]
